#Project Information
site_name: Data Structures and Algorithms
site_description: Simplified data structures, algorithms and competitive coding questions.
site_author: Tejas Pawar
site_url: https://tejas-pawar.github.io/DSA/
theme:
  name: material

extra_css:
  - css/katex.css
  - css/custom.css
  - https://cdn.jsdelivr.net/npm/katex@0.13.11/dist/katex.min.css

extra_javascript:
  - js/katex.js
  - https://cdn.jsdelivr.net/npm/katex@0.13.11/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.13.11/dist/contrib/auto-render.min.js

nav:
  - Preface: index.md
  - Data Structures:
      - Basic: DataStructures/basic.md
      - Advanced: DataStructures/advanced.md
      - Very Advanced: DataStructures/vadvanced.md
  - Algorithms:
      - Basic:
          - Sorting: Algorithms/basic/sorting.md
          #- Tree Traversal: Algorithms/basic/treetraversal.md
          - Graph Traversal: Algorithms/basic/graph.md
      #- Advanced:
          #- General: Algorithms/advanced/general.md
          #- Divide And Conquer: Algorithms/advanced/dnc.md
          #- Greedy: Algorithms/advanced/greedy.md
          #- DP: Algorithms/advanced/dp.md
          #- Graph: Algorithms/advanced/graph.md
  - Competitive Coding:
      #- Easy:
          #- General: CompCoding/easy/general.md
          # Trees: CompCoding/easy/trees.md
          #- Graphs: CompCoding/easy/graphs.md
          #- DP: CompCoding/easy/dp.md
      #- Medium: CompCoding/medium.md
      - Hard: 
        - Tree: CompCoding/Hard/tree.md
      #- Combo Problems:
          #- Catalan Numbers: CompCoding/combo/catalan.md
          #- Overlapping Intervals: CompCoding/combo/overlapping_intervals.md
  - Techniques You Must Know:
      #- Easy: Techniques/mustknow_easy.md
      - Difficult: Techniques/mustknow_difficult.md
  - System Design:
      - Resources: SystemDesign/system_design_resources.md
  - Object Oriented:
      - Resources: OOP/oop_resources.md






